title: Express Coffee India
description: Express coffee started in February 27, 2017 with a goal of bringing the pure taste of our historic coffee tradition into millions of Indians across the country.
url: https://expresscoffeeindia.com
enforce_ssl: expresscoffeeindia.com
logo: /images/logox500.png
lang: en_IN

# shop: https://shop.expresscoffeeindia.com/
shop: '#'


analytics: UA-115749700-1

facebook:
 app_id:
 publisher:
 admins:


google_site_verification:


form-entry: https://docs.google.com/spreadsheets/d/14KCGIs5lSbP1rYAPBSvmlX52FbErwj_34L-u3fu2crU/edit?usp=forms_web_b#gid=373835449




#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4, h5, h6, link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title, input, form, iframe, textarea]
  comments: [<!--, -->]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

sass:
    style: compressed

plugins:
    - jekyll-seo-tag
